-- Migration: initial_schema
-- Project: ThreadDrop
-- Generated by: Database Engineer Agent

BEGIN;

-- ── TABLES ──────────────────────────────────────────────────────────────────

-- Table: leads (Captures Name and Email for waitlist)
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── INDEXES ─────────────────────────────────────────────────────────────────

-- Index for lead email lookups
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);

-- ── UPDATED_AT TRIGGER ───────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'set_updated_at_leads') THEN
    CREATE TRIGGER set_updated_at_leads
      BEFORE UPDATE ON leads
      FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();
  END IF;
END $$;

-- ── ROW LEVEL SECURITY ───────────────────────────────────────────────────────

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Enable insert: Public (Allow users to submit the waitlist form)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'leads' AND policyname = 'Allow public lead submission'
  ) THEN
    CREATE POLICY "Allow public lead submission" ON leads
      FOR INSERT WITH CHECK (true);
  END IF;
END $$;

-- Enable select: Authenticated (Admin only)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'leads' AND policyname = 'Allow authenticated selection'
  ) THEN
    CREATE POLICY "Allow authenticated selection" ON leads
      FOR SELECT TO authenticated USING (true);
  END IF;
END $$;

COMMIT;